SELECT * FROM CUSTOMERS;

SELECT firstName FROM CUSTOMERS;

SELECT firstName FROM CUSTOMERS WHERE CUSTOMERID = 1;

UPDATE CUSTOMERS SET firstName = 'Lerato', lastName = 'Mabitso' WHERE CUSTOMERID = 1;

DELETE FROM CUSTOMERS WHERE CUSTOMERID = 2;

SELECT COUNT(DISTINCT STATUS) FROM ORDERS;

SELECT MAX(AMOUNT) FROM PAYMENTS;

SELECT * FROM PRODUCTS WHERE BUYPRICE>100 AND BUYPRICE<600;

SELECT * FROM CUSTOMERS WHERE COUNTRY = 'Germany' AND CITY = 'Berlin';

SELECT * FROM CUSTOMERS WHERE CITY = 'Cape Town' OR CITY = 'Durban';

SELECT * FROM PRODUCTS WHERE BUYPRICE > 500;

SELECT SUM(AMOUNT) FROM PAYMENTS;

SELECT COUNT(STATUS) FROM ORDERS WHERE STATUS = 'Shipped';

SELECT AVG(BUYPRICE) FROM PRODUCTS;

SELECT AVG(BUYPRICE * 12) FROM PRODUCTS;

SELECT * FROM PAYMENTS INNER JOIN CUSTOMERS ON PAYMENTS.CUSTOMERID = CUSTOMERS.CUSTOMERID;

SELECT * FROM PRODUCTS WHERE DESCRIPTION LIKE 'Turnable front wheels%';